### ISSUE TITLE
Specifying "--compatibility" flag with docker-compose project

### ISSUE THREAD

**Issue by STDGA** [Microsoft/DockerTools#104]
Hi,
I am developing on windows 10 machine and because Windows 10 supports only "HyperV" isolation and  it is limited to 1GB memory by default,i created my docker compose file like this:

```
version: '3.6'

services:
  website:
    ports:
      - "80"
    volumes:
      - .\storage\Data:C:\inetpub\sc\Data
    deploy:
      resources:
        limits:
          memory: 5GB
        reservations:
          memory: 3GB
    build:
      dockerfile: Dockerfile
      args:
        source: obj/Docker/empty
    
    volumes:
      - .\storage\Website\:C:\inetpub\sc\website
    entrypoint: powershell -Command "C:/DebugBoot.ps1;C:/remote_debugger/x64/msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646;C:/ServiceMonitor.exe w3svc;"

```

Docker 3.x supports swarm mode and if i want to use mem_limit features from docker compose 2.x then i must pass the --compatibility flag to docker compose (see the discussion here: https://github.com/docker/compose/issues/4513 and https://github.com/docker/compose/pull/5684), this will works for me from command prompt:

` docker-compose --compatibility up -d --force-recreate`

My base image is :"microsoft/aspnet:4.7.1-windowsservercore-ltsc2016"

**I couldn't find a way to pass in the --compatibility in visual studio, is it possible at all?**
