### ISSUE TITLE
Configurable path to executable in container for debugging

### ISSUE THREAD

**Issue by sanderdegroot** [Microsoft/DockerTools#119]
Simplified example - I have the following docker-compose file, located at C:\Development\Solution\docker-compose.yml:
```
version: '3.4'

services:
  myservice:
    image: project
    build:
      context: ..
      dockerfile: ./Solution/Project/Dockerfile
```

Note that the build context is the directory C:\Development\Solution (in the default docker-compose file that gets generated when Docker support is added to a project, the build context is the project folder, C:\Development\Solution\Project in this case).

When I build this docker-compose project in Debug mode, Visual Studio generated C:\Development\Solution\obj\Docker\docker-compose.vs.debug.g.yml with the following contents:
```
version: '3.4'

services:
  myservice:
    image: project:dev
    build:
      target: base
    volumes:
      - C:\Development\Solution:C:\app
      - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\Remote Debugger:C:\remote_debugger:ro
    entrypoint: cmd /c "set DISABLE_PERFORMANCE_DEBUGGER=1 & C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646"
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\app\\bin\\Debug\\Program.exe"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
```

The above compose file mounts C:\Development\Solution, my build context, to C:\ app in the container. It then presumably tries to attach the debugger to the value of the label `com.microsoft.visualstudio.debuggee.program`, `C:\\app\\bin\\Debug\\Program.exe`, but in reality Program.exe is located at C:\app\Project\bin\Debug\Program.exe, so the debugger fails to attach.

The build context needs to be C:\Development\Solution in this case, as we have files in parent folders that need to be copied into the image for Release builds.

Is there a way to specify the path the debugger should attach to (the `com.microsoft.visualstudio.debuggee.program` label) or which folder on the host should be volume mounted to C:\app by docker-compose.vs.debug.g.yml? I haven't been able to find a way to accomplish either one.

**Comment by haniamr** [comment]
Hi @sanderdegroot,

Thanks for reporting this. You can create a file named "docker-compose.vs.debug.yml" in your docker-compose project (you'll have to add it manually) with the following contents:

```
version: '3.4'

services:
  myservice:
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\app\\Project\\bin\\Debug\\Program.exe"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
```

Doing so, this file will be the last in the chain of files when docker-compose commands are called so it always takes precedence.
