### ISSUE TITLE
Cannot change hosting environment while debugging

### ISSUE THREAD

**Issue by steveoh** [Microsoft/DockerTools#122]
```
services:
  cache:
    image: redis:latest
  db:
    environment:
      POSTGRES_DB: webapi
      POSTGRES_USER: postgres
    image: postgres:10.4
    ports:
    - published: 5432
      target: 5432
    volumes:
    - pgdata:/var/lib/postgresql/data:rw
  webapi-core:
    build:
      context: /Users/sgourley/Projects/webapi-core
      dockerfile: api.mapserv.utah.gov/Dockerfile
      target: base
    entrypoint: tail -f /dev/null
    environment:
      ASPNETCORE_ENVIRONMENT: DockerDevelopment
      ASPNETCORE_URLS: http://+:1337
      DOTNET_USE_POLLING_FILE_WATCHER: '1'
      NUGET_FALLBACK_PACKAGES: /root/.nuget/fallbackpackages
    image: webapi:dev
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages
        --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp2.1/api.mapserv.utah.gov.dll'
      com.microsoft.visualstudio.debuggee.killprogram: /bin/bash -c "if PID=$$(pidof
        -x dotnet); then kill $$PID; fi"
      com.microsoft.visualstudio.debuggee.program: dotnet
      com.microsoft.visualstudio.debuggee.workingdirectory: /app
    links:
    - cache
    - db
    ports:
    - published: 1337
      target: 1337
    volumes:
    - /Users/sgourley/Projects/webapi-core/api.mapserv.utah.gov:/app:rw
    - /Users/sgourley/.vsdbg/vs2017u5:/remote_debugger:ro
    - /usr/local/share/dotnet/sdk/NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
    - /Users/sgourley/.nuget/packages:/root/.nuget/packages:ro
version: '3.6'
volumes:
  pgdata:
    external: true
    name: pgdata
```

hosting env is still Development
