### ISSUE TITLE
Cannot create container for service server

### ISSUE THREAD

**Issue by ibocon** [Microsoft/DockerTools#128]
## Description of the issue

Cannot create container for service server

Error Message:
The DOCKER_REGISTRY variable is not set. Defaulting to a blank string.

## Context information (for bug reports)

I change my Windows edition from Home to Enterprise.
I got an error from Docker for Windows because of Docker Toolbox's system environment variable.
Therefore, I delete Docker related system environment variable and re-install Docker for Windows.
Then I got an error on building ASP.NET Core MVC template project.

```
Output of "docker-compose version"
```
docker-compose version 1.21.1, build 7641a569
docker-py version: 3.2.1
CPython version: 3.6.4
OpenSSL version: OpenSSL 1.0.2k  26 Jan 2017
```
Output of "docker version"
```
Client:
 Version:      18.03.1-ce
 API version:  1.37
 Go version:   go1.9.5
 Git commit:   9ee9f40
 Built:        Thu Apr 26 07:12:48 2018
 OS/Arch:      windows/amd64
 Experimental: false
 Orchestrator: swarm

Server:
 Engine:
  Version:      18.03.1-ce
  API version:  1.37 (minimum version 1.24)
  Go version:   go1.9.5
  Git commit:   9ee9f40
  Built:        Thu Apr 26 07:21:42 2018
  OS/Arch:      windows/amd64
  Experimental: false
```
Output of "docker-compose config"
```
ERROR:
        Can't find a suitable configuration file in this directory or any
        parent. Are you in the right directory?

        Supported filenames: docker-compose.yml, docker-compose.yaml

## Steps to reproduce the issue

1. Update ASP.NET Core from 2.0 to 2.1
2. Update Windows 10 Home to Enterprise
3. Create ASP.NET Core MVC Controller template project
4. Build "Docker"
 
### Stacktrace / full error message
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		The DOCKER_REGISTRY variable is not set. Defaulting to a blank string.
Building server
Creating dockercompose2577525810590707085_server_1 ... 
Creating dockercompose2577525810590707085_server_1 ... error
ERROR: for dockercompose2577525810590707085_server_1  Cannot create container for service server: invalid volume specification: '/c/Program Files (x86)/dotnet/sdk/NuGetFallbackFolder:c:\.nuget\fallbackpackages:ro'
ERROR: for server  Cannot create container for service server: invalid volume specification: '/c/Program Files (x86)/dotnet/sdk/NuGetFallbackFolder:c:\.nuget\fallbackpackages:ro'
Encountered errors while bringing up the project..

For more troubleshooting information, go to http://aka.ms/DockerToolsTroubleshooting	docker-compose	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets	363	
```
## Additional information
[Stackoverflow](https://stackoverflow.com/questions/51077809/docker-accidentally-delete-system-environment-variables)
[docker-compose](https://github.com/docker/compose/issues/6049#issuecomment-401091323)

**Comment by haniamr** [comment]
Hi @ibocon,

Thanks for reporting this. It seems that the nuget package folders defined in that project are not based on Windows specifications for some reason, you can double check that under `{PathToRepo}\SolutionName\ProjectName\obj\{ProjectName}.csproj.nuget.g.props`.

The properties we use are `NugetPackageRoot `and `NugetPackageFolders` so you need to make sure that those paths are correct.

**Comment by ibocon** [comment]
Hi @haniamr ,

Thanks to reply to issue.

```
<NuGetPackageRoot Condition=" '$(NuGetPackageRoot)' == '' ">$(UserProfile)\.nuget\packages\</NuGetPackageRoot>
<NuGetPackageFolders Condition=" '$(NuGetPackageFolders)' == '' ">C:\Users\Name\.nuget\packages\;C:\Program Files (x86)\dotnet\sdk\NuGetFallbackFolder</NuGetPackageFolders>
```

I can't notice any issue with `NugetPackageRoot` or `NugetPackageFolders` path...

**Comment by haniamr** [comment]
It is temp but I'm not sure if it gets deleted on clean (did a trial and it didn't), however the path does look normal to me. Would you share with me the full output for the build log? Also the generated docker-compose.vs.debug.yml file that you can find under obj\Docker.

**Comment by ibocon** [comment]
Here is  my
> docker-compose.vs.debug.g.yml  

```
version: '3.4'

services:
  mangoslab:
    image: mangoslab:dev
    build:
      target: base
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      - NUGET_FALLBACK_PACKAGES=c:\.nuget\fallbackpackages
    volumes:
      - C:\Users\TBD\Documents\MANGOSLAB\Project\mangoslab\Mangoslab:C:\app
      - C:\Users\TBD\onecoremsvsmon\15.0.27703.2026:C:\remote_debugger:ro
      - C:\Users\TBD\.nuget\packages\:c:\.nuget\packages:ro
      - C:\Program Files (x86)\dotnet\sdk\NuGetFallbackFolder:c:\.nuget\fallbackpackages:ro
    entrypoint: C:\\remote_debugger\\x64\\msvsmon.exe /noauth /anyuser /silent /nostatus /noclrwarn /nosecuritywarn /nofirewallwarn /nowowwarn /timeout:2147483646
    labels:
      com.microsoft.visualstudio.debuggee.program: "\"C:\\Program Files\\dotnet\\dotnet.exe\""
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath c:\\.nuget\\packages --additionalProbingPath c:\\.nuget\\fallbackpackages  bin\\Debug\\netcoreapp2.1\\Mangoslab.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "C:\\remote_debugger\\x64\\utils\\KillProcess.exe dotnet.exe"
```

**Comment by haniamr** [comment]
Alright, it looks to me that the problem might be docker related, since the generated file seem to have the correct paths.

One test you can try is to create a simple docker-compose file and dockerfile with the following contents:

> docker-compose.yml
```
version: '3.4'

services:
  helloworldservice:
    image: helloworld:dev
    build:
      context: .
      target: base
      dockerfile: dockerfile
    volumes:
      - C:\Users\TBD\onecoremsvsmon\15.0.27703.2026:C:\remote_debugger:ro
```
> dockerfile
 `FROM hello-world as base`

Then open a cmd in that directory and run: `docker-compose up`

Will that work?
