### ISSUE TITLE
VS 15.3 Preview does not allows to override "/remote_debugger"  "/root/.nuget/packages:ro" and other volumes

### ISSUE THREAD

**Issue by dmitriyse** [Microsoft/DockerTools#13]
I am using VS 2017 vs DOCKER_HOST pointing to a remote linux machine.

In 15.2 - I am able to override mounts:
      - /mnt/${USERNAME}/.nuget/packages:/root/.nuget/packages:ro

In 15.3, it is impossible due to auto-generated files:
docker-compose.vs.debug.g.yml 
with content
```yml
version: '3'

services:
  my-project:
    image: my-project:dev
    build:
      args:
        source: ${DOCKER_BUILD_SOURCE}
    volumes:
      - C:\my-project:/app
      - ${NUGET_PACKAGES}:/root/.nuget/packages:ro
      - ${VSDBG_PATH}:/remote_debugger:ro
    entrypoint: tail -f /dev/null
```
Please provide some way to override this volumes:
      - C:\my-project:/app
      - ${NUGET_PACKAGES}:/root/.nuget/packages:ro
      - ${VSDBG_PATH}:/remote_debugger:ro

Or provide some way to auto mount this volumes to a remote linux machine

**Comment by dmitriyse** [comment]
Currently I need to hacking up target "DockerCreateComposeVsGeneratedFiles" to cut out this lines:
      - C:\my-project:/app
      - ${NUGET_PACKAGES}:/root/.nuget/packages:ro
      - ${VSDBG_PATH}:/remote_debugger:ro

**Comment by dazhao-msft** [comment]
@dmitriyse you can set NUGET_PACKAGES with the path on your host machine. It will be honored by the docker-compose files.

**Comment by dmitriyse** [comment]
1) I cannot override "C:\my-project\path":/app  volume, in this case there are no any variable like ${PROJECT_DIR}.  (On remote DOCKER_HOST this pass is different than local client project path).

2) ${VSDBG_PATH} can be different for different projects, so it is not so useful to work with ENV vars.
(Probably it can be solved easily, if I can change Debian8 to Ubuntu16.04 vsdbg version in VS docker project settings)
3) I tried to define NUGET_PACKAGES, but I still got finally
"- .:/root/.nuget/packages:ro" volume definition


4) If 3) problem will be solved, than probably next problem will appear:
${NUGET_PACKAGES} will not support inner environment variables:
when I do 
```cmd
setx NUGET_PACKAGES /mnt/nuget-cache/${COMPUTERNAME}
```
I will get "- .:/root/.nuget/packages:ro"
"- /mnt/nuget-cache/${COMPUTERNAME}:/root/.nuget/packages:ro"

----

Please add detection of defined volumes:
/app
/root/.nuget/packages:ro
/remote_debugger:ro

and exclude those definitions from the generated 
"C:\my-solution\my-project\obj\Docker\docker-compose.vs.debug.g.yml"

**Comment by dazhao-msft** [comment]
@dmitriyse Can you please describe your scenario a bit more? We don't really support mounting folders from a remote Linux machine today. 

Particularly, I want to understand why you don't have those folders on you Windows host machine (e.g. c:\your-project). As long as you can build ASP.NET Core projects with VS on the machine, those folders should exist so I'm not sure why you need to volume mount a different folder.

**Comment by dmitriyse** [comment]
Actually I am managed to connect remote linux host with VS 2015.2.
Near to everything already exists in the current tools version.

Local linux virtual machines not well suited to our products, we are using Nvidia GPUs and other specialized hardware.


In short words I use the following:
set DOCKER_HOST=my-big-remote-host:2375
set COMPOSE_CONVERT_WINDOWS_PATHS=1

```yml
version: '2'
#Run this on docker host on startup: docker volume create --name=nvidia_driver_381.22 -d nvidia-docker
volumes:
  nvidia_driver_381.22:
    external: true
services:
  my-service:
    volumes:
      #- <my-big-remote-host path>:<container path>
     # some special mounts
     # and VS connectivity:
     - <manually-copied-ubuntu16.04-clrdbg>:clrdbg:ro
     - <autofs-mounted-nuget-cache/${COMPUTERNAME}>:/nuget/packages (that is symbolic linked to /root/.nuget inside container)
     - <autofs-mounted-src/$(COMPUTERNAME}/project>:/app
```

Some another tricks (like convention-based shares on every developer machine) and 

GOTCHA! all team members from different developer machines works on a single powerful docker host with a special hardware.

In 15.3 this scenario becomes broken.
Currently I use DIRTY DIRTY workaround - hijack 
docker-compose.exe that cuts of -f ".....\docker-compose.vs.debug.g.yml" and calls docker-compose-original.exe.
----
Please do not kill this very powerful user experience and free developers from DIRTY DIRTY work.
