### ISSUE TITLE
Value cannot be null, Parameter name: stream

### ISSUE THREAD

**Issue by da1rren** [Microsoft/DockerTools#141]
Hey,

We recently added a new container to our compose project using the following configuration:

```
  onboard.api.functions:
    image: onboard-api-functions
    build:
      context: .
      dockerfile: Onboard.Api.Functions\Dockerfile
```

I can then see this in the output:
```
2>  onboard.api.functions:
2>    build:
2>      context: C:\Projects\Repositories\Onboard.Api\src\Onboard.Api
2>      dockerfile: Onboard.Api.Functions\Dockerfile
2>    image: onboard-api-functions
2>version: '3.4'
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(299,5): error : Value cannot be null.
2>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(299,5): error : Parameter name: stream
```

If I point the dockerfile parameter at another file it seems to work.  Futhermore if I prefix the dockerfile path with a '\\' I am able to build.  However when attempting to run docker-compose blows up.

This issue appears to have only started when I upgraded to visual studio 15.8.0 as previously this was working.
