### ISSUE TITLE
build hangs during docker-compose build image phase in Visual Studio 2017

### ISSUE THREAD

**Issue by kavhad** [Microsoft/DockerTools#150]
Visual studio 2017 build hangs when building a solution with docker-compose project.

Microsoft Windows [Version 10.0.17134.285]
Docker version 18.06.1-ce, build e68fc7a

docker-compose.yml
```
version: '3.4'

services:
  myService:
    image: ${DOCKER_REGISTRY}x/test
    build:
      args:
        TARGET_SERVERCORE_VERSION: ${TARGET_SERVERCORE_VERSION}
      context: .\MyServiceProject
      dockerfile: Dockerfile
    environment:
    - "DbConnectionString=${DbConnectionString}"
    - "ELASTICSEARCH_URL=${ELASTICSEARCH_URL}"

```
.env file
```

DbConnectionString=xxxxxxxxx
TARGET_SERVERCORE_VERSION=1803
ELASTICSEARCH_URL=http://elasticsearch:9200
DOCKER_REGISTRY=

```

When build hangs, the following lines shows up in docker logs (C:\ProgramData\Docker\service.txt):

```
[09:41:57.805][WindowsDaemon  ][Info   ] debug: Calling POST /v1.30/build?t=+x%2test&q=False&nocache=False&rm=True&forcerm=False&pull=False&dockerfile=Dockerfile&buildargs=%7B%22TARGET_SERVERCORE_VERSION%22%3A+%221803%22%7D
[09:41:57.806][WindowsDaemon  ][Info   ] debug: FIXME: Got an API for which error does not match any expected type!!!: invalid reference format [module=api error_type=*errors.errorString]
```

If I remove the ${DOCKER_REGISTRY} parameter in the docker-compose.yml file build works again.

**Update**

To reproduce add DOCKER_REGISTRY as system environment variable in windows, with a single space char as value. Local .env file won't override windows global environment variable. Open a new command prompt and run docker-compose build as stated above.
