### ISSUE TITLE
CreateComposeVsGeneratedFiles task fails with error "Value cannot be null"

### ISSUE THREAD

**Issue by tj-cappelletti** [Microsoft/DockerTools#174]
I'm working on setting up a new project to use Docker Compose to deploy a web app and a database to two different containers for local development. When I save the compose file Visual Studio picks up the change and immediately runs `docker-compose` and it runs successfully. My images get created and I'm able to start them from the command line without issue. The second I try to build the solution (using any of the many ways to do so) the build task `CreateComposeVsGeneratedFiles` fails and gives me an error message that simply is not helpful:

```
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(291,5): error : Value cannot be null.
C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(291,5): error : Parameter name: stream
```

I've tried cleaning the solution performing a rebuild with no success. I also tried removing all of the local images and containers to see if maybe there was a force command not being applied somewhere but that didn't work either. I've also looked through many issues on the web, some point to old problems that were closed as they were fixed in earlier releases of VS while others point to issues with doing Azure Functions in a container which I am not doing.

Here is my current compose file:
```yaml
version: '3.4'

services:
  mvc:
    image: ${DOCKER_REGISTRY-}tsacodingchallengesubmissionsmvc
    build:
      context: .
      dockerfile: Tsa.CodingChallenge.Submissions.Mvc/Dockerfile
    depends_on:
      - db

  db:
    image: ${DOCKER_REGISTRY-}tsacodingchallengesubmissionsdb
    build:
      context: .
      dockerfile: Tsa.CodingChallenge.Submissions.Database/Dockerfile
```

My override file:
```yaml
version: '3.4'

services:
  mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44327
    ports:
      - "11467:80"
      - "44327:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

  db:
    ports:
      - "1438:1433"
```

The MVC `Dockerfile`:
```dockerfile
FROM microsoft/dotnet:2.2-aspnetcore-runtime AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM microsoft/dotnet:2.2-sdk AS build
WORKDIR /src
COPY Tsa.CodingChallenge.Submissions.Mvc/Tsa.CodingChallenge.Submissions.Mvc.csproj Tsa.CodingChallenge.Submissions.Mvc/
COPY Tsa.CodingChallenge.Submissions.Core/Tsa.CodingChallenge.Submissions.Core.csproj Tsa.CodingChallenge.Submissions.Core/
RUN dotnet restore Tsa.CodingChallenge.Submissions.Mvc/Tsa.CodingChallenge.Submissions.Mvc.csproj
COPY . .
WORKDIR /src/Tsa.CodingChallenge.Submissions.Mvc
RUN dotnet build Tsa.CodingChallenge.Submissions.Mvc.csproj -c Release -o /app

FROM build AS publish
RUN dotnet publish Tsa.CodingChallenge.Submissions.Mvc.csproj -c Release -o /app

FROM base AS final
WORKDIR /app
COPY --from=publish /app .
ENTRYPOINT ["dotnet", "Tsa.CodingChallenge.Submissions.Mvc.dll"]
```
And my DB `Dockerfile`:
```dockerfile
FROM mcr.microsoft.com/mssql/server:2017-latest

COPY scripts/Tsa.CodingChallenge.Submissions.Database_Create.sql /create-db.sql
COPY scripts/create-sql-database.sh /

ENV ACCEPT_EULA Y
ENV SA_PASSWORD rIMdEnfnHj395cFO

RUN /create-sql-database.sh

CMD [ "/opt/mssql/bin/sqlservr" ]
```

I'm currently running the following tool set:

- Visual Studio 2017 Enterprise (15.9.10)
- Docker Engine 18.09.2 (both client and server)

Let me know if you need more details or would like the source code. This project will eventually be made open source so I can post it GitHub ahead of time if need be.
