### ISSUE TITLE
Does VS Docker CLI  not respect the Build Network?

### ISSUE THREAD

**Issue by endeffects** [microsoft/DockerTools#188]
I'm running multiple docker containers, each has it's own compose file.
I also run a nuget container within the docker host. 

The feed runs within a seperate network called proget-internal-net.
To make it available for the build process i've added it 
to the web application build section.

This works well from console. But when i start Visual Studio (2019)
and run the composer project the restore fails.
So i'm not able to debug my web application.

Setup for the nuget container:

```
networks:
  proget-internal-net:  <---
    name: proget-internal-net
    driver: bridge
  proget-isolated-net:
    name: proget-isolated-net
    driver: bridge
    internal: true

services:
  proget:
    image: inedo/proget:latest
    container_name: proget
    ....
    ports:
      - 10100:80
    networks: 
      - proget-internal-net
      - proget-isolated-net
    links:
      - proget_db

```

Setup for the web application container:

```
networks:
  webapi-public-net:
    name: webapi-public-net
    driver: bridge
  proget-internal-net:   <---
    name: proget-internal-net
    external: true

services:
  webapp:
    image: ${DOCKER_REGISTRY-}webapp
    container_name: webapp
    restart: always
    networks: 
      - webapi-public-net
    build:
      context: .
      dockerfile: WebApp/Dockerfile
      network: proget-internal-net  <---

```
