### ISSUE TITLE
Volumes added when running through Visual Studio different to running docker-compose up

### ISSUE THREAD

**Issue by WilliamT-Streamba** [microsoft/DockerTools#197]
Is there a reason why the volumes mounted in an ASP.NET Core project during development are different to those specified in the docker-compose.override.yaml file?

When trying to run docker compose outside of Visual Studio my application breaks as the ClientApp directory, used by JavascriptServices, only includes the production build.

My understanding was that docker-compose.override.yaml reflects the configuration of the development environment but Visual Studio is performing additional steps that aren't documented in any config files.

**Comment by bwateratmsft** [comment]
@WilliamT-Streamba When debugging in Visual Studio, the auto-generated obj\Docker\docker-compose.vs.debug.g.yml is used in addition to docker-compose.yml and docker-compose.override.yml. This maps in source, the remote debugger, and user secrets in order to debug.

**Comment by WilliamT-Streamba** [comment]
Thank you! I updated docker-compose.override.yml to the following:

````yaml
services:
  web:
    image: web
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44372
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "40142:80"
      - "44372:443"
    volumes:
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ./Web/ClientApp:/app/ClientApp
````

CHOKIDAR_USEPOLLING=true is set to allow file watching with webpack dev server.
 ./Web/ClientApp is mounted in /app/ClientApp so the source is available during development for webpack dev server
