### ISSUE TITLE
Deploying auto-generated Visual Studio Docker configuration on Linux

### ISSUE THREAD

**Issue by piotrek-k** [microsoft/DockerTools#198]
I thought that one of the main advantages of Docker for developers is that one can create single container configuration that can be easily deployed, without changes, on any platform (Linux, Windows).

That's not exactly true for Docker tools on Visual Studio 2019. I've created an ASP.net project and Visual Studio automatically generated docker and docker-compose configuration. I can without any problems run it using Visual Studio 2019 (on Windows using linux container). Then, I've pushed my code to git repo and cloned it on other device (Linux).

When I run `docker-compose up` on that other device, I can see such error:
> Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.

After some investigation I found out, that it's because Visual Studio uses some additional config file (`\obj\Docker\docker-compose.vs.debug.g.yml`) that is platform dependent and is not included in git repo. It contains paths to folders that are relevant only on my Windows device.

Am I using it wrong? Is it OK, that docker configuration works in Visual Studio only? Is it a bug? Should I configure HTTPS endpoint by hand (I mean: modify automatically generated Docker configuration so it configure HTTPS at startup)? If so, what is the purpose of such generator if I need to, either way, write configuration myself?

(issue initially created [MicrosoftDocs/visualstudio-docs](https://github.com/MicrosoftDocs/visualstudio-docs/issues/3545#event-2445140194). They redirected me here)

**Comment by bwateratmsft** [comment]
You need to do some configuration when deploying the image for the HTTPS certificate. Within Visual Studio, a self-signed development certificate is used, but this certificate is not appropriate for production scenarios.

@haniamr are you familiar with production HTTPS setup?

**Comment by haniamr** [comment]
As Brandon mentioned, VS runs the "dev-certs" tool to trust and export a self-signed certificate in the container however this won't work if you manually run `docker-compose up` on a different machine.

You have to ensure Kestrel knows which certificate it should use, which is explained here https://devblogs.microsoft.com/aspnet/asp-net-core-2-1-https-improvements/ in more details, and also ensure this certificate is available in the container. Since this is machine dependent, it cannot be something that gets generated as part of the template(s) and run across different environments, specifically in Linux as quoted from the blog post: 

> On Linux there isn't a standard way across distros to trust the certificate, so you'll need to perform the distro specific guidance for trusting the development certificate.

Let me know if you need more info and I'll be happy to help.

**Comment by piotrek-k** [comment]
Thank you for quick response.
I've made the following steps ([based on this article](https://devblogs.microsoft.com/aspnet/configuring-https-in-asp-net-core-across-different-platforms/)).
Created `https.config` file:
```
[ req ]
default_bits       = 2048
default_md         = sha256
default_keyfile    = key.pem
prompt             = no
encrypt_key        = no

distinguished_name = req_distinguished_name
req_extensions     = v3_req
x509_extensions    = v3_req

[ req_distinguished_name ]
commonName             = "localhost"

[ v3_req ]
subjectAltName      = DNS:localhost
basicConstraints    = critical, CA:false
keyUsage            = critical, keyEncipherment
extendedKeyUsage    = critical, 1.3.6.1.5.5.7.3.1
```

Run 3 commands:
```
openssl req -config https.config -new -out csr.pem
openssl x509 -req -days 365 -extfile https.config -extensions v3_req -in csr.pem -signkey key.pem -out https.crt
openssl pkcs12 -export -out https.pfx -inkey key.pem -in https.crt -password pass:ddd123
```

Now I've got `https.pfx` that, I suppose, is my https certificate. It lies here: `/home/piotrek/Desktop/SyncedDB/other/https`

Then I've added some Kestrel settings to `appsettings.Development.json`. 
```
{
  "Logging": {
    "LogLevel": {
      "Default": "Debug",
      "System": "Information",
      "Microsoft": "Information"
    }
  },
  "Kestrel": {
    "Certificates": {
      "Default": {
        "Path": "/root/.aspnet/https/https.pfx",
        "Password": "ddd123"
      }
    }
  }
}

```
In `docker-compose.override.yml` I've configured volume (so that my newly created certificate from `/home/piotrek/Desktop/SyncedDB/other/https` goes to `/root/.aspnet/https` in container).
```
version: "3.4"

services:
  synceddb:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - ASPNETCORE_HTTPS_PORT=44361
    ports:
      - "10002:80"
      - "44361:443"
    volumes:
      - /home/piotrek/Desktop/SyncedDB/other/https:/root/.aspnet/https:ro
```

Here is my `docker-compose.yml`:
```
version: "3.4"

services:
  mongo:
    # config omitted

  mongo-express:
    # config omitted

  synceddb:
    image: ${DOCKER_REGISTRY-}synceddb
    ports:
      - 13000:13000
    build:
      context: .
      dockerfile: SyncedDB/Dockerfile
    depends_on:
      - mongo

```
To run it I use:
```
sudo docker-compose -f docker-compose.yml -f docker-compose.override.yml up --force-recreate
```

I'm still getting:
> Unable to start Kestrel.
> System.InvalidOperationException: Unable to configure HTTPS endpoint. No server certificate was specified, and the default developer certificate could not be found.

Is there something I'm missing here?

PS: Is there any documentation of all those environment variables used in docker-compose files? I'm struggling with interpreting things like `${DOCKER_REGISTRY-}`, variables in `environment:` section of docker.compose.yml which Visual Studio generated without informing about their purpose.

**Comment by piotrek-k** [comment]
Problem solved. I used this command:
 ```$ dotnet dev-certs https -ep %USERPROFILE%\.aspnet\https\aspnetapp.pfx -p somepassword```
to generate certificate.

My current Docker configuration:
```
version: '3.4'

services:
  mongo:
      # not relevant

  mongo-express:
      # not relevant

  synceddb:
      image: ${DOCKER_REGISTRY-}synceddb
      ports:
        - 13000:13000
        - "10002:80"
        - "44361:443"
      build:
        context: .
        dockerfile: SyncedDB/Dockerfile
      depends_on:
        - mongo
      environment:
        - ASPNETCORE_ENVIRONMENT=Development
        - ASPNETCORE_URLS=https://+:443;http://+:80
        - ASPNETCORE_HTTPS_PORT=44361
        - ASPNETCORE_Kestrel__Certificates__Default__Password=somepassword
        - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx
      volumes:
        - ${HOME}/.aspnet/https:/https
```

Thanks again for explanation.
