### ISSUE TITLE
Running Docker-Compose project in Release Configuration Errors out

### ISSUE THREAD

**Issue by zikhan** [microsoft/DockerTools#210]
When launching a Docker-Compose project in VS2019, and the configuration is set to Release, the a dotnet command being run is generated with --additionalProbingPath parameters, which the dotnet sdk gives this message.
![image](https://user-images.githubusercontent.com/8488326/64812346-a7ca2700-d564-11e9-9020-587fffce9889.png)

The base image being used is `mcr.microsoft.com/dotnet/core/sdk:2.2`.

**Comment by sgreenmsft** [comment]
@zikhan - Can you provide the contents of obj\docker\docker-compose.vs.release.g.yml?

**Comment by zikhan** [comment]
docker-compose.vs.release.g.yml
```yml
version: '3.4'

services:
  vc-administration:
    build:
      labels:
        com.microsoft.created-by: "visual-studio"
        com.microsoft.visual-studio.project-name: "vc-administration"
    volumes:
      - C:\Users\zovin.khanmohammed\vsdbg\vs2017u5:/remote_debugger:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro

    entrypoint: tail -f /dev/null
    labels:
      com.microsoft.visualstudio.debuggee.program: "dotnet"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"vc-administration.dll\""
      com.microsoft.visualstudio.debuggee.workingdirectory: "/app"
      com.microsoft.visualstudio.debuggee.killprogram: "/bin/sh -c \"if PID=$$(pidof dotnet); then kill $$PID; fi\""
```
