### ISSUE TITLE
Support ASP.NET Core user secrets

### ISSUE THREAD

**Issue by natemcmaster** [microsoft/DockerTools#24]
_Original post by @chrisoverzero: https://github.com/aspnet/Configuration/issues/659_

------

**Summary**: User secrets cannot (easily, portably) be used with Visual Studio's "Docker Support" feature for ASP.NET Core projects.

Hi! I've been using User Secrets for a while in several ASP.NET Core projects. My company is evaluating a move to Docker for deployments, and – as part of that evaluation – I activated the Docker Support feature in Visual Studio. After this, the application completely failed to reference my secrets.

I've worked around this for my own support by bind-mounting (in `docker-compose.override.yml`) the `secrets.json` file on my development box to the correct location in the Linux container, but this seems to violate [Microsoft's advice][]:

> You should not write code that depends on the location or format of the data saved
> with the Secret Manager tool, as these implementation details might change.

[Microsoft's advice]: https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets#how-the-secret-manager-tool-works

...in addition to not being portable between our Windows and Linux developers.

#### Versions of things
- Microsoft.Extensions.Configuration.UserSecrets: 1.1.1
- Microsoft.Extensions.SecretManager.Tools: 1.0.0
- Visual Studio: 15.1 (26403.7)

-------

_Comment by @natemcmaster: https://github.com/aspnet/Configuration/issues/659#issuecomment-301912883_

The advice was written with authors of third-party class libraries and tools in mind. The location of the files is not "under contract" so your docker-compose file might break in future versions. However, until that happens, volume mounting the user secrets location for **development** environments is fine, and seems like something Docker Tooling could consider doing by default.

That said, mounting UserSecrets for **production** is not recommended. For production secrets, checkout https://github.com/aspnet/Configuration/tree/dev/src/Microsoft.Extensions.Configuration.DockerSecrets

**Comment by natemcmaster** [comment]
I think the simplest solution would be for docker tools to volume mount `%APPDATA%\microsoft\UserSecrets\` to `~/.microsoft/usersecrets/` when creating a new container.

cc @sgreenmsft @yanchenw

**Comment by TotzkePaul** [comment]
I can't seem to figure out how to even do this in docker compose. I don't think you can you can use `%APPDATA%` directly so I use the full folder path. No errors but my secrets don't appear.  I'm not sure if the aspnetcore:2.0 docker image has
https://docs.microsoft.com/en-us/aspnet/core/security/app-secrets?tabs=visual-studio

csproj:
`<UserSecretsId>918f68d1-483b-46d1-8556-717af3673207</UserSecretsId>`

docker-compose:
```
version: '2'
services:
  postgres:
    container_name: 'postgres'
    image: postgres
    restart: always
    ports:
       - 5432:5432
  main.web:
    image: main.web
    ports:
       - 8080:80
    volumes:
      - C:\Users\FakeUser\AppData\Roaming\Microsoft\UserSecrets\:/.microsoft/usersecrets/
    build:
      context: ./Main.Web
      dockerfile: Dockerfile
    depends_on:
     - "postgres"
```

startup.cs:
```
public Startup(IHostingEnvironment env)
        {
            var builder = new ConfigurationBuilder()
                .SetBasePath(env.ContentRootPath)
                .AddJsonFile("appsettings.json", optional: true, reloadOnChange: true)
                //this works:    .AddJsonFile("/.microsoft/usersecrets/918f68d1-483b-46d1-8556-717af3673207/secrets.json", optional: false, reloadOnChange: true)
                .AddJsonFile($"appsettings.{env.EnvironmentName}.json", optional: true); 

            if (env.IsDevelopment())
            { --this is hit, does not throw an error but no config values are pulled in
                builder.AddUserSecrets<Startup>(optional:false);
            }

            Configuration = builder.Build();
        }
```
