### ISSUE TITLE
gRPC Service: SSL Connection Error

### ISSUE THREAD

**Issue by Yairsno1** [microsoft/DockerTools#249]
I have a solution that contains 3 service projects; 

1. WebAPI
2. gRPC service 1 (ConfigService)
3. gRPC service 2 (DataAccessService)

The call stack is: Browser --> WebAPI -->  gRPC service 2 --> gRPC service 1

I have added Container Orchestration Support to the service projects, the following docker-compose YAML file was created
```
version: '3.4'

services:
  configservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro   
      
  dataaccessservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "80"
      - "443"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  webapiservice:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "5000:80"
```

The containers are created, along with certificates and secretes for the couple of gRPC services, nice and smooth.

![certs](https://user-images.githubusercontent.com/25245708/79685149-0ebc6680-823f-11ea-972e-9fd742a5896b.png)

The problem is during debugging while running inside the containers, a call to gRPC's method throws an exception:

> System.Net.Http.HttpRequestException: 'The SSL connection could not be established, see inner exception.'
> 
> AuthenticationException: The remote certificate is invalid according to the validation procedure. 
> 

Linux Containers on Windows
Target Framework: .NET Core 3.1
Microsoft.VisualStudio.Azure.Containers.Tools.Targets 1.10.8
Visual Studio Tool for Containers 1.0
Visual Studio 2019 16.5.4
