### ISSUE TITLE
override "com.microsoft.visualstudio.debuggee.arguments" from build options in project properties or docker-compose

### ISSUE THREAD

**Issue by mhamri** [microsoft/DockerTools#264]
I have a cli app that supposed to run in docker. changing the build option on project properties doesn't change the arguments passed to the cli in docker.debug

![image](https://user-images.githubusercontent.com/8991783/87656596-467a7200-c78c-11ea-831c-d4250549c1ed.png)

not being able to do that, or override it in the docker-compose make it hard to debug a cli app. best is if we can override this through the docker-compose since we can't set multiple build argument but we can create multiple docker-compose files for debugging and production.

**Comment by pratiksanglikar** [comment]
Hi @mhamri , thank you for reporting this issue. I was able to reproduce this issue. It is now under investigation.

**Comment by pratiksanglikar** [comment]
Hi @mhamri , upon further investigation, I found out that you could override the `com.microsoft.visualstudio.debuggee.arguments` property. To override the property, please create a file - `docker-compose.vs.debug.yml` at the same location where your `docker-compose.yml` file is located.
In this newly created file, override the label as - 
```
version: '3.4'

services:
  console1:
    labels:
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath /root/.nuget/packages --additionalProbingPath /root/.nuget/fallbackpackages  \"/app/bin/Debug/netcoreapp3.1/Console1.dll\" <your command line arguments here>"
```
For more information on this topic, please check the following link - 
[docker compose file labels](https://docs.microsoft.com/en-us/visualstudio/containers/docker-compose-properties?view=vs-2019#docker-compose-file-labels)
