### ISSUE TITLE
Visual studio 2019 docker compose deserialization error

### ISSUE THREAD

**Issue by stefanodesimone** [microsoft/DockerTools#291]
Hi,
I have added a net core 3.1 class library  to my solution and referenced in API project. 
Before adding the class library everything was fine, but now i have an error:
_A non-critical error occurred while getting containers ready.  Your project will continue to function normally.  The error was: (Line: 4, Col: 12, Idx: 55) - (Line: 4, Col: 18, Idx: 61): Exception during deserialization_

If i try to build docker compose project the error is 
Exception during deserialization
```
<CreateComposeVsGeneratedFiles DockerComposeProjectPath="$(DockerComposeProjectPath)"
                                   DockerComposeBaseFilePath="$(DockerComposeBaseFilePath)"
                                   AdditionalComposeFilePaths ="$(AdditionalComposeFilePaths)"
                                   DockerDevelopmentMode="$(DockerDevelopmentMode)"
                                   DockerVsDbgPath="$(DockerVsDbgPath)"
                                   DockerMsVsMonPath="$(DockerMsVsMonPath)"
                                   DockerOneCoreMsVsMonPath="$(DockerOneCoreMsVsMonPath)"
                                   ServiceReferences="@(DockerServiceReferences)"
                                   ErrorLogFilePath="$(ErrorLogFilePath)"
                                   SkipDefaultImageLabels ="$(SkipDefaultImageLabels)"/>
```
my compose file
```
version: '3.4'
services:
  envoygateway:
    build: Envoy/
    ports:
      - "9901:9901"
      - "10000:10000" #for http
      - "10001:10001" #for https
    volumes:
      - ./Envoy/envoy.yaml:/etc/envoy/envoy.yaml
      - ./Envoy/https.crt:/etc/ssl/certs/https.crt
      - ./Envoy/key.pem:/etc/ssl/certs/key.pem
```
My compose override
```
version: '3.4'

services:
  users.api:
    image: ${DOCKER_REGISTRY-}usersapi
    build:
     context: .
     dockerfile: Users.API/Dockerfile
    ports:
      - "8080:80"
      - "8081:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8081"
      ASPNETCORE_ENVIRONMENT: "Development"
    volumes:
      - ${APPDATA}\microsoft\UserSecrets\:/root/.microsoft/usersecrets
      - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/
```

My docker file
```
FROM mcr.microsoft.com/dotnet/core/aspnet:3.1-buster-slim AS base
WORKDIR /app


FROM mcr.microsoft.com/dotnet/core/sdk:3.1-buster AS build
WORKDIR /app
COPY ["Users.API/Users.API.csproj", "Users.API/"]
COPY ["Users.API.Core/Users.API.Core.csproj", "Users.API.Core/"]
RUN dotnet restore "Users.API/Users.API.csproj"
COPY . .
WORKDIR "/app/Users.API"
RUN dotnet build "Users.API.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Users.API.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "Users.API.dll"]
```

In any case if i launch via `docker-compose up  --build` everything run!

I'm currently running the following tool set:
Visual studio professional 2019 Version 16.8.4
Docker engine Server and client  Version:  20.10.2

Let me know if you want other details
Thanks a lot
Stefano
