### ISSUE TITLE
Docker Compose Build Url

### ISSUE THREAD

**Issue by mattpetrick** [microsoft/DockerTools#308]
```
version: '3.5'

services:
  hello:
    build: https://github.com/docker-library/hello-world.git#:amd64/hello-world/nanoserver-1809
```
works from command line (docker-compose up) but from visual studio produces the error:

> 2>C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(209,5): error CTC1000: The given path's format is not supported.
