### ISSUE TITLE
Renaming the Image name doesn't get used when debugging w/F5

### ISSUE THREAD

**Issue by SteveLasker** [Microsoft/DockerTools#31]
Create an ASP.NET Core Web App
Add Docker Support
Choose Windows
Open the docker-compose.yml file
Change the image value to something
```
services:
  web:
    image: webish
    build:
      context: .\Web
      dockerfile: Dockerfile
```
Hit F5
Run docker images
Notice the image name is still web
I should be able to rename the image to reflect my actual image name. It may include my registry, another name like frontendmarketingweb
