### ISSUE TITLE
CTC1000 Expected 'MappingStart', got 'SequenceStart' for 'depends_on' in VS 17.3.4

### ISSUE THREAD

**Issue by cjbush** [microsoft/DockerTools#356]
I have a docker-compose.yml file that's valid and works with using docker-compose up on the command line, but the Microsoft.VisualStudio.Docker.Compose.targets file is barfing on the DockerGetServiceReferences task with the following error:

| Code | Description | Project | File | Line |
| --- | --- | --- | --- | --- |
| CTC1000 | (Line: 6, Col: 5, Idx: 97) - (Line: 6, Col: 6, Idx: 98): Expected 'MappingStart', got 'SequenceStart' (at Line: 6, Col: 5, Idx: 97). | docker-compose | Microsoft.VisualStudio.Docker.Compose.targets | 201 |

The docker-compose.yml file is pretty basic, just spinning up a SQL server image and a RabbitMq image. I've isolated it to the depends_on clause. If I remove it, it builds correctly. If not, the build fails.

``` yaml
version: '3.4'

services:
  sql-data:
    image: mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
    depends_on: 
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.8.20-management   
```

This behavior started when I upgraded Visual Studio to 17.3.4 and 17.3.5, but I believe I was on one of the 17.2.x releases, so I'm not sure exactly when it got introduced. Any insight is appreciated.

**Comment by danegsta** [comment]
We have a fix for this issue that will ship in VS 2022 17.4 preview 3, but you should also be able to work around it by switching your depends_on declaration from the short syntax version to the corresponding long syntax version (see: https://docs.docker.com/compose/compose-file/#depends_on). For the sample compose yaml you provided, that would look like:

```
version: '3.4'

services:
  sql-data:
    image: mcr.microsoft.com/mssql/server:2017-CU24-ubuntu-16.04
    depends_on: 
      rabbitmq:
        condition: service_started

  rabbitmq:
    image: rabbitmq:3.8.20-management
```
