### ISSUE TITLE
Visual Studio 2022 17.3.5: Docker-Compose needs rebuild to debug new changes

### ISSUE THREAD

**Issue by algruenwald** [microsoft/DockerTools#358]
Whenever I change something in my ASP.NET Microservice, I need to rebuild the Project or everything for the changes to be available for debugging on the container, otherwise It will try to debug outdated source which ends up with failing my breakpoints.

This problem occurs since updating to the latest version of Visual Studio / Docker. I'm using VS 2022 17.3.5 with Docker 4.12.0 and Container Tools 1.17.0.

It seems like like the problem is, that my docker-compose.dcproj (and launchSettings.json) does not rebuild my local projects, this could also be because my changes are in a referenced project.

docker-compose.dcproj
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project ToolsVersion="15.0" Sdk="Microsoft.Docker.Sdk">
  <PropertyGroup Label="Globals">
    <ProjectVersion>2.1</ProjectVersion>
    <DockerTargetOS>Linux</DockerTargetOS>
    <ProjectGuid>3665ba0b-49be-4e79-9c48-a1657281978a</ProjectGuid>
    <DockerLaunchAction>None</DockerLaunchAction>
    <DockerServiceUrl>{Scheme}://localhost:{ServicePort}/{Scheme}://{ServiceHost}:{ServicePort}</DockerServiceUrl>
    <DockerServiceName>configurationservice.api</DockerServiceName>
  </PropertyGroup>
  <ItemGroup>
    <None Include=".dockerignore" />
    <None Include="docker-compose.override.yml">
      <DependentUpon>docker-compose.yml</DependentUpon>
    </None>
    <None Include="docker-compose.yml" />
  </ItemGroup>
</Project>
```

launchSettings.json
```json
{
  "profiles": {
    "Docker Compose": {
      "commandName": "DockerCompose",
      "commandVersion": "1.0",
      "serviceActions": {
        "configurationservice.api": "StartDebugging",
        "configurationservice.api-dapr": "StartWithoutDebugging",
        "identityservice.api": "StartDebugging",
        "identityservice.api-dapr": "StartWithoutDebugging",
        "legacyproxyservice.api": "StartDebugging",
        "legacyproxyservice.api-dapr": "StartWithoutDebugging",
        "yarp": "StartDebugging",
        "yarp-dapr": "StartWithoutDebugging",
        "redis": "StartWithoutDebugging",
        "zipkin": "StartWithoutDebugging"
      }
    }
  }
}
```

I expect my visual studio projects (named like the docker-compose containers) to be rebuilt whenever they're out of date. When I rebuild all manually, breakpoints and debugging work like expected. I guess it actually rebuild the whole solution when building manually causing this to work.

**Comment by aschwab** [comment]
Hi @danegsta , thanks for your reply, yes I do use dependencies, here are my docker-compose Files:

```yaml
version: '3.4'

services:
  yarp:
    image: ${DOCKER_REGISTRY-}yarp
    build:
      context: .
      dockerfile: Yarp/Yarp/Dockerfile
    depends_on:
    - identityservice.api
    - configurationservice.api
    - legacyproxyservice.api
  yarp-dapr:
    image: "daprio/daprd:1.4.2"
    depends_on:
    - yarp
    network_mode: "service:yarp"

  configurationservice.api:
    image: ${DOCKER_REGISTRY-}configurationserviceapi
    build:
      context: .
      dockerfile: ConfigurationService/ConfigurationService.API/Dockerfile
  configurationservice.api-dapr:
    image: "daprio/daprd:1.4.2"
    depends_on:
    - configurationservice.api
    - redis
    network_mode: "service:configurationservice.api"

  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: IdentityService/IdentityService.API/Dockerfile
    depends_on:
    - configurationservice.api
  identityservice.api-dapr:
    image: "daprio/daprd:1.4.2"
    depends_on:
    - identityservice.api
    - redis
    network_mode: "service:identityservice.api"

  legacyproxyservice.api:
    image: ${DOCKER_REGISTRY-}legacyproxyserviceapi
    build:
      context: .
      dockerfile: LegacyProxyService/LegacyProxyService.API/Dockerfile
    depends_on:
    - configurationservice.api
  legacyproxyservice.api-dapr:
    image: "daprio/daprd:1.4.2"
    depends_on:
    - legacyproxyservice.api
    network_mode: "service:legacyproxyservice.api"

  redis:
    image: "redis:6.2.6-alpine"

  zipkin:
    image: openzipkin/zipkin-slim
```

```yaml
version: '3.4'

services:

  yarp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DAPR_HTTP_PORT=3500
    ports:
      - "7000:80"
      - "7001:443"
      - "50001:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    dns:
      - 8.8.8.8
      - 127.0.0.11

  yarp-dapr:
    command: ["./daprd",
     "-app-id", "apigateway",
     "-app-port", "80",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/dapr-config.yaml",
     "-log-level", "info"]
    volumes:
        - "./dapr-components/docker:/dapr"

  identityservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "7100:80"
      - "7101:443"
      - "50002:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identityservice.api-dapr:
    command: ["./daprd",
     "-app-id", "identityservice",
     "-app-port", "80",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/dapr-config.yaml",
     "-log-level", "info"]
    volumes:
        - "./dapr-components/docker:/dapr"

  configurationservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "7200:80"
      - "7201:443"
      - "50004:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  configurationservice.api-dapr:
    command: ["./daprd",
     "-app-id", "configurationservice",
     "-app-port", "80",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/dapr-config.yaml",
     "-log-level", "info"]
    volumes:
        - "./dapr-components/docker:/dapr"

  legacyproxyservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "7300:80"
      - "7301:443"
      - "50005:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  legacyproxyservice.api-dapr:
    command: ["./daprd",
     "-app-id", "legacyproxyservice",
     "-app-port", "80",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/dapr-config.yaml",
     "-log-level", "debug"]
    volumes:
        - "./dapr-components/docker:/dapr"

  redis:
    ports:
      - "6379:6379"

  zipkin:
    ports:
      - "9411:9411"
```

Please don't be irritated by some paths / file / project-names, I removed the customer- / product name.

**Comment by aschwab** [comment]
I removed all dependencies from my the microservice-containers (not the side-cars), did a clean on the solution and the docker-compose project and built the while solution.

I did not fix the problem and whats also interesting is, that I get the error that the main dll's for the projects could not be copied which actually means that the projects from the docker-compose Project haven't been built at all when having docker-compose set as startup project.

The changes I make in my project are not directly in the web-project itself but in a referenced library, maybe that's why it's not tracked?!

Also my Containers window throws an exception (An error occured while attempting to refresh the containers.):
![image](https://user-images.githubusercontent.com/736468/193754267-93dbd1cc-06b4-428b-9dff-cf7fb46b302c.png)

**Comment by danegsta** [comment]
The issue with depends_on is a bug that is preventing the extension from parsing the short form the the configuration; we've created a fix that will ship with VS 17.4, but you can workaround the issue in the meantime by switching from the short version of the syntax to the long version (see: https://docs.docker.com/compose/compose-file/#depends_on). You would also have to remove the version: '3.4' declaration from the top of your compose yaml files as the long form is only supported in the current compose spec (which no longer uses a version declaration, but is backwards compatible with the earlier 3.x and 2.x specifications). 

For example,

```
depends_on:
- identityservice.api
- redis
```

would become

```
depends_on:
  identityservice.api:
    condition: service_started
  redis:
    condition: service_started
```

Making that change for every usage of depends_on should allow the extension to properly track and report the service projects as build dependencies.

For the COM error, I'd usually recommend trying to repair your VS install as a first step to see if that fixes the problem; sometimes various component caches get out of sync and a repair can ensure VS is loading all required assemblies at the correct times.

**Comment by aschwab** [comment]
I've tried to apply your workaround by replacing all of the depends_on statements with the long form, but the problem persists. I still need to manually rebuild to debug / run the newer version of the source after I applied my changes.

Is there any other known issue according to project / container mapping?

**Comment by aschwab** [comment]
@danegsta I also tried this with VS 17.3.0 (Fixed Installer), but the problem also persists. Are there any news on this? If this helps I can offer to debug this together, my Discord-Handle would be Alsc#4353.

**Comment by danegsta** [comment]
@aschwab would you be able to share your updated docker-compose.yaml and docker-compose.override.yaml files? I can run them through our parser to see if anything else there is causing issues. Which service projects have a ProjectReference to IdentityService.Domain? If you update the service projects, but not not the IdentityService.Domain project, do the changes get picked up during a normal build/F5?

**Comment by aschwab** [comment]
@danegsta here are my updated Docker-Compose files:

```yaml
services:
  yarp:
    image: ${DOCKER_REGISTRY-}yarp
    build:
      context: .
      dockerfile: Yarp/Yarp/Dockerfile
    depends_on:
      identityservice.api:
        condition: service_started
      configurationservice.api:
        condition: service_started
      legacyproxyservice.api:
        condition: service_started
  yarp-dapr:
    image: "daprio/daprd:1.4.2"
    depends_on:
      yarp:
        condition: service_started
    network_mode: "service:yarp"

  configurationservice.api:
    image: ${DOCKER_REGISTRY-}configurationserviceapi
    build:
      context: .
      dockerfile: ConfigurationService/ConfigurationService.API/Dockerfile
  configurationservice.api-dapr:
    image: "daprio/daprd:1.4.2"
    depends_on:
      configurationservice.api:
        condition: service_started
      redis:
        condition: service_started
    network_mode: "service:configurationservice.api"

  identityservice.api:
    image: ${DOCKER_REGISTRY-}identityserviceapi
    build:
      context: .
      dockerfile: IdentityService/IdentityService.API/Dockerfile
    depends_on:
      configurationservice.api:
        condition: service_started
  identityservice.api-dapr:
    image: "daprio/daprd:1.4.2"
    depends_on:
      identityservice.api:
        condition: service_started
      redis:
        condition: service_started
    network_mode: "service:identityservice.api"

  legacyproxyservice.api:
    image: ${DOCKER_REGISTRY-}legacyproxyserviceapi
    build:
      context: .
      dockerfile: LegacyProxyService/LegacyProxyService.API/Dockerfile
    depends_on:
      configurationservice.api:
        condition: service_started
  legacyproxyservice.api-dapr:
    image: "daprio/daprd:1.4.2"
    depends_on:
      legacyproxyservice.api:
        condition: service_started
    network_mode: "service:legacyproxyservice.api"

  redis:
    image: "redis:6.2.6-alpine"

  zipkin:
    image: openzipkin/zipkin-slim
```

```yaml
services:

  yarp:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
      - DAPR_HTTP_PORT=3500
    ports:
      - "7000:80"
      - "7001:443"
      - "50001:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro
    dns:
      - 8.8.8.8
      - 127.0.0.11

  yarp-dapr:
    command: ["./daprd",
     "-app-id", "apigateway",
     "-app-port", "80",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/dapr-config.yaml",
     "-log-level", "info"]
    volumes:
        - "./dapr-components/docker:/dapr"

  identityservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "7100:80"
      - "7101:443"
      - "50002:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  identityservice.api-dapr:
    command: ["./daprd",
     "-app-id", "identityservice",
     "-app-port", "80",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/dapr-config.yaml",
     "-log-level", "info"]
    volumes:
        - "./dapr-components/docker:/dapr"

  configurationservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "7200:80"
      - "7201:443"
      - "50004:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  configurationservice.api-dapr:
    command: ["./daprd",
     "-app-id", "configurationservice",
     "-app-port", "80",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/dapr-config.yaml",
     "-log-level", "info"]
    volumes:
        - "./dapr-components/docker:/dapr"

  legacyproxyservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:443;http://+:80
    ports:
      - "7300:80"
      - "7301:443"
      - "50005:50001"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/root/.aspnet/https:ro

  legacyproxyservice.api-dapr:
    command: ["./daprd",
     "-app-id", "legacyproxyservice",
     "-app-port", "80",
     "-dapr-http-port", "3500",
     "-components-path", "/dapr/components",
     "-config", "/dapr/dapr-config.yaml",
     "-log-level", "debug"]
    volumes:
        - "./dapr-components/docker:/dapr"

  redis:
    ports:
      - "6379:6379"

  zipkin:
    ports:
      - "9411:9411"
```

The depends_on attribute doesn't change a thing, not even removing it.

The only Service-Project referencing IdentityService.Domain is IdentityService.API which is also the Name of the Container (Docker-Compose). It does not help changing anything in the IdentityService.API project, it also does not build when changing something in the "main"-project.
