### ISSUE TITLE
Cannot start Docker debug with VS2017 15.3

### ISSUE THREAD

**Issue by joye-ramone** [microsoft/DockerTools#37]
After upgrade to latest VS 2017 15.3 I cannot start debug of Docker container from VS.
Reproducible with any kind of .net core projects (console, asp.net) and with any version of .net core.

I also tried to start VS with admin rights, restart my box and stop and start docker.

Error message: Operation aborted (Exception from HRESULT: 0x80004004 (E_ABORT))
Docker log:
```
docker-compose -f "C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\docker-compose.yml" -f "C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\docker-compose.override.yml" -f "C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\obj\Docker\docker-compose.vs.debug.g.yml" -p dockercompose9756074155277170669 config
services:
  consoleapp1:
    build:
      args:
        source: obj/Docker/empty/
      context: C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1
      dockerfile: Dockerfile
    entrypoint: tail -f /dev/null
    environment:
      NUGET_FALLBACK_PACKAGES: /root/.nuget/fallbackpackages
    image: consoleapp1:dev
    labels:
      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath /root/.nuget/packages
        --additionalProbingPath /root/.nuget/fallbackpackages  bin/Debug/netcoreapp2.0/ConsoleApp1.dll'
      com.microsoft.visualstudio.debuggee.killprogram: /bin/bash -c "if PID=$(pidof
        -x dotnet); then kill $PID; fi"
      com.microsoft.visualstudio.debuggee.program: dotnet
      com.microsoft.visualstudio.debuggee.workingdirectory: /app
    volumes:
    - C:\Users\Sergii_Tkachenko\Documents\Visual Studio 2017\Projects\ConsoleApp1\ConsoleApp1:/app:rw
    - C:\Users\Sergii_Tkachenko\vsdbg:/remote_debugger:ro
    - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:/root/.nuget/fallbackpackages:ro
    - C:\Users\Sergii_Tkachenko\.nuget\packages:/root/.nuget/packages:ro
version: '3.0'
docker  ps --filter "status=running" --filter "name=dockercompose9756074155277170669_consoleapp1_" --format {{.ID}} -n 1
1f2a3ec3b102
```

But, I can see that image created and container is up and running using docker -ps:
docker ps
CONTAINER ID        IMAGE               COMMAND               CREATED             STATUS              PORTS               NAMES
1f2a3ec3b102        consoleapp1:dev     "tail -f /dev/null"   16 hours ago        Up About a minute                       dockercompose9756074155277170669_consoleapp1_1
