### ISSUE TITLE
`{ProjectDir\}.IdentityService\AzureServiceAuth\tokenprovider.json` created when container debug is started

### ISSUE THREAD

**Issue by ggirard07** [microsoft/DockerTools#387]
I have a project in my solution that keeps creating a file at path `{ProjectDir\}.IdentityService\AzureServiceAuth\tokenprovider.json` every time I start a docker compose debug. The same file is not created when debugging the project directly without using Docker tooling.
Any idea why it is happening to just one of the projects part of same solution & docker-compose?

@danegsta mentioned [in this thread](https://github.com/microsoft/DockerTools/issues/345#issuecomment-1574119077) that it could be related to custom volume mount in docker compose. The only one I setup myself is for mounting dotnet secrets to my non-root user in containers with:
```yaml
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
```
I do not think this is related as all my projects use this mount but only a specific one is affected.

**Comment by danegsta** [comment]
@ggirard07 would you be able to share a snippet of the service configuration from your docker-compose for the specific impacted project?

**Comment by ggirard07** [comment]
Here is the part relevant to the project involved. Please note in full docker compose I have multiple API projects involved, each with SQL migrations mounted in db container, but only a single API project has this file creation issue...
```yaml
services:
  api:
      image: ${DOCKER_REGISTRY-}prj/api
      build:
        context: .
        dockerfile: src/My.API/Dockerfile
      environment:
        ASPNETCORE_ENVIRONMENT: ${ASPNETCORE_ENVIRONMENT}
        SqlContext: "cs"
      ports:
        - 18080:8080
      volumes:
        - ${APPDATA}/Microsoft/UserSecrets:/root/.microsoft/usersecrets:ro
      depends_on:
        sql:
          condition: service_healthy

  sql:
    image: ${DOCKER_REGISTRY-}prj/sql
    build:
      context: .
      dockerfile: tests/infrastructure/sql/Dockerfile
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: ${SA_PASSWORD}
      MIGRATIONS_PATH: ${MIGRATIONS_PATH}
    init: true
    ports:
      - 8484:1433
    tmpfs:
      - /tmp/app
    volumes:
      - ./src/My.API/Migrations:${MIGRATIONS_PATH}/API:ro
    healthcheck:
      test: "[ -f /tmp/app/migrations.ready ]"
      interval: 5s
    cap_add:
      - "SYS_PTRACE"
```
