### ISSUE TITLE
Docker Compose build target fails on build since upgrade to VS 15.3

### ISSUE THREAD

**Issue by brainwipe** [Microsoft/DockerTools#43]
I had a docker-compose working fine, I've not upgraded Visual Studio 2017 (to 15.3.3) and Docker (17.06.1-ce-win24 13025) the dcproj fails:

```
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(279,5): error : Value cannot be null.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Professional\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(279,5): error : Parameter name: stream
```

The offending line is:

```xml
<CreateComposeVsGeneratedFiles DockerComposeProjectPath="$(DockerComposeProjectPath)"
                                   DockerDevelopmentMode="$(DockerDevelopmentMode)"
                                   DockerVsDbgPath="$(DockerVsDbgPath)"
                                   DockerMsVsMonPath="$(DockerMsVsMonPath)"
                                   DockerOneCoreMsVsMonPath="$(DockerOneCoreMsVsMonPath)" />
```

When I loaded the project after updating Visual Studio, it asked me to upgrade the compose files. I agreed and it only changed the version number from 2 to 3.

My compose is:

```yml
version: '3'

services:
  mcodatabase:
    image: mcodatabase
    build:
      context: ./Data
      dockerfile: Dockerfile
    restart: always
    ports:
       - 9876:5432
    environment:
      POSTGRES_USER: mcodevuser
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mcodev
    volumes:
     - postgresdata:/var/lib/postgresql/data
    networks:
     - mconetwork

  mcoidentityserver:
    image: mcoidentityserver
    build:
      context: ./Mco.IdentityServer
      dockerfile: Dockerfile
    environment:
      IDENTITY_ISSUER: "http://10.0.75.1:5000"
    ports:
       - 5000:5000
    networks:
     - mconetwork

  mcoapi:
    image: mcoapi
    build:
      context: ./Mco.Api
      dockerfile: Dockerfile
    environment:
      IDENTITY_AUTHORITY: "http://mcoidentityserver:5000"
    ports:
       - 56107:80
    links:
     - mcodatabase
     - mcoidentityserver
    depends_on:
     - "mcodatabase"
     - "mcoidentityserver"
    networks:
     - mconetwork
    
  mcotestclient:
    image: mcotestclient
    build: 
      context: ./Client
      dockerfile: Dockerfile
    ports:
     - 56108:80
    networks:
     - mconetwork

volumes:
  postgresdata:

networks:
  mconetwork:
     driver: bridge
```

**Comment by dbreshears** [comment]
This is fixed in the 15.4 release that is planned for next week.

**Comment by micnyk** [comment]
Any updates on this issue?
When fix will be released?

**Comment by brainwipe** [comment]
This was fixed in 15.4

**Comment by dbreshears** [comment]
@brainwipe, thanks for the confirmation.   @micnyk,   this issue was fixed.   I'll close this issue for now but open another issue if still having problems after updating to 15.4

**Comment by mphadeuspacy** [comment]
I am getting the same issue on VS version 15.7.3

**Comment by mphadeuspacy** [comment]
![errorvs](https://user-images.githubusercontent.com/6725803/41097485-683d08dc-6a58-11e8-8cc4-187567393595.PNG)

See attached with error messages

**Comment by AlphaGit** [comment]
@mphadeuspacy I'm finding this same issue in VS 15.7.3 too.

A workaround I've been able to use is to ensure that Dockerfiles are **not** at the root level of a project.

So, if your docker-compose contains this:

```yaml
version: '3'

services:
  myService:
    build:
      context: .
      dockerfile: MyProject/Dockerfile
```

Move the dockerfile into a subfolder:

```yaml
version: '3'

services:
  myService:
    build:
      context: .
      dockerfile: MyProject/Docker/Dockerfile
```
