### ISSUE TITLE
Docker Compose healthcheck between two containerized ASP.NET Core projs causes hang

### ISSUE THREAD

**Issue by brandonh-msft** [microsoft/DockerTools#440]
I have two containers defined in my `docker-compose`:

<details><summary>docker-compose.yml</summary>

```yml
services:
  cis.copilot.orchestrator:
    image: ${DOCKER_REGISTRY-}ciscopilotorchestrator
    build:
      context: .
      dockerfile: ./CIS.CoPilot.Orchestrator/Dockerfile
    healthcheck:
      test: "curl -fLk --no-progress-meter http://localhost:8080/healthcheck"
      interval: 0s
      timeout: 3s
      retries: 1
      start_period: 10s
      start_interval: 5s

  cis.copilot.netagent:
    image: ${DOCKER_REGISTRY-}ciscopilotnetagent
    build:
      context: .
      dockerfile: CIS.CoPilot.NetAgent/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      cis.copilot.orchestrator:
        condition: service_healthy
```

</details>

with an override file of

<details><summary>docker-compose.override.yml</summary>

```yml
services:
  cis.copilot.orchestrator:
    build:
      args:
      - BUILD_CONFIGURATION=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Logging__LogLevel__Default=Trace
    entrypoint: ["dotnet", "CIS.CoPilot.Orchestrator.dll"]
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    expose:
      - 8080
      - 8081
    ports:
      - 8080:8080
      - 8081:8081
  cis.copilot.netagent:
    build:
      args:
      - BUILD_CONFIGURATION=Debug
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - Logging__LogLevel__Default=Trace
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
```

</details>

I found that, when VS is used to build & deploy the containers, the `entrypoint` of the container is changed to use dotnet roll forward:

```json
		"Entrypoint": [
			"dotnet",
			"--roll-forward",
			"Major",
			"/VSTools/DistrolessHelper/DistrolessHelper.dll",
			"--wait"
		],
```

Instead of respecting the endpoint defined in the Dockerfile for the orchestrator:

<details><summary>orchestrator DOCKERFILE</summary>

```
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS publish
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY . .
WORKDIR "/src/CIS.CoPilot.Orchestrator"
RUN dotnet dev-certs https --trust -q
RUN dotnet publish "./CIS.CoPilot.Orchestrator.csproj" -c $BUILD_CONFIGURATION -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:8.0

RUN apt-get update && \
	apt-get install -y curl

WORKDIR /app
COPY --from=publish /app/publish .
USER app

ENTRYPOINT ["dotnet", "CIS.CoPilot.Orchestrator.dll"]
```

</details>

This is the only diff I can tell between native `docker compose up` and using VS though, admittedly, I haven't done a full diff between both `INSPECT` areas of the resulting container groups.

I have tried augmenting my dcproj with

```xml
<ContainerDevelopmentMode>Regular</ContainerDevelopmentMode>
<DockerFastModeEnabled>false</DockerFastModeEnabled>
```

as well as forcing the `entrypoint` value in my `docker-compose.override.yml` but so far have had no luck.

When I `docker compose up` from terminal, everything works exactly as it should.

How do I fix this?

**Comment by NCarlsonMSFT** [comment]
@brandonh-msft I'm not able to reproduce a hang, but debugging is broken for me when using depends_on with the health check.

Work-around:
Use
Right-Click on the project->Add->VS Compose Override Files
![image](https://github.com/user-attachments/assets/c622a980-7423-4377-9a05-a4102a2505f5)
This adds a `docker-compose.vs.debug.yml` and `docker-compose.vs.release.yml`
In those files you can add:
```yml
services:
  cis.copilot.netagent:
    depends_on:
      cis.copilot.orchestrator:
        condition: service_started
```
To change the depends_on condition, but only when running through VS

FYI The Entrypoint change isn't just to support Fast mode, it's also used in regular mode so that the service can be started under the debugger, but it does mean that depends_on doesn't work reliably.
