### ISSUE TITLE
[Preview] Feedback requested on enhancements to compose launch in 17.13 Preview 1

### ISSUE THREAD

**Issue by NCarlsonMSFT** [microsoft/DockerTools#448]
We've made some big changes in how the `.dcproj` launches compose services in 17.13 Preview 1 and we need your help to validate that the new experience is meeting your needs!

## depends_on
We've added a new way of launching compose (triggered by setting the msbuild property `DependencyAwareStart` to `true`) that allows for debugging when declaring dependencies between services.
### Turning it on
```xml
  <PropertyGroup>
    <DependencyAwareStart>true</DependencyAwareStart>
  </PropertyGroup>
```
### What works
| |service_started|service_healthy|service_completed_successfully|
|--|--|--|--|
|linux|✔️|✔️|.NET 6+ (not AOT compiled)|
|windows|✔️|✔️|❌|

## replicas / scale
No opt-in needed, this should just work now!
### What works
```yml
  backend:
    image: ${DOCKER_REGISTRY-}backend
    scale: 2
```
--or--
```yml
  backend:
    image: ${DOCKER_REGISTRY-}backend
    deploy:
      replicas: 2
```

**Comment by jiangyi1985** [comment]
this works for me
```yaml
deploy:
      replicas: 2
```
but this doesn't
```yaml
scale: 2
```

Visual Studio 17.13.0 Preview 2.1
Docker Desktop v4.26.1

**Comment by NCarlsonMSFT** [comment]
@jiangyi1985 can you provide more context on what is not working?
I just tested on 17.13 Preview 2.1 with:
```yml
services:
  webapplication2:
    image: ${DOCKER_REGISTRY-}webapplication2
    scale: 2
    build:
      context: .
      dockerfile: WebApplication2/Dockerfile
```
And got the two instances as expected
