### ISSUE TITLE
DockerCleanWorkspace Doesn't Cleanup Volumes Defined In docker-compose.yml

### ISSUE THREAD

**Issue by brantburnett** [Microsoft/DockerTools#46]
If your docker-compose file defines virtual volumes to be shared between multiple containers, these are left in place during DockerCleanWorkspace.  The next build and run will still have data in these volumes, despite the expectation that the run should be clean.

If `docker-compose down` is instead run with the `-v` command line argument, the volumes will be deleted.

Example docker-compose.yml:

```yaml
version: '3'

services:
  couchbase:
    image: btburnett3/couchbasefakeit:latest
    volumes:
    - "./couchbase:/startup"
    - "nodestatus:/nodestatus"
    networks:
    - network
    ports:
    - "8091:8091"
  service:
    image: service
    build:
      context: ./Service
      dockerfile: Dockerfile
    environment:
      Couchbase__Servers__0: http://couchbase:8091/
      READY_FILE: /nodestatus/initialized
    networks:
    - network
    volumes:
    - "nodestatus:/nodestatus"
    depends_on:
    - couchbase
networks:
  network:
volumes:
  nodestatus:
```

In this example, the file /nodestatus/initialized is written by one container to indicate that initialization is complete.  The main service being debugged should wait for this file before startup because it will be unable to connect.  During simple builds this file will still be present, resulting in fast startup and intact data.

But during a Rebuild operation the "couchbase" service is destroyed and restarted.  If the nodestatus volume isn't also destroyed, the /nodestatus/initialized file is still present during the next startup, causing unexpected behavior.  The only way to fix this currently is to manually delete the volume on the command line.
