### ISSUE TITLE
default asp.net core web debug error

### ISSUE THREAD

**Issue by CAH-FlyChen** [Microsoft/DockerTools#63]
i create a default  asp.net core web app
enable windows docker support
F5
i got error

```
正在还原 NuGet 程序包...
若要阻止 NuGet 在生成期间还原程序包，请打开 Visual Studio 的“选项”对话框，单击“程序包管理器”节点，然后取消选中“允许 NuGet 在生成期间下载缺少的程序包”。
1>------ 已启动生成: 项目: docker-compose, 配置: Release Any CPU ------
1>docker  version --format {{.Server.Os}}
1>windows
1>docker-compose -f "C:\TEMP\test\docker-compose.yml" -f "C:\TEMP\test\docker-compose.override.yml" -p dockercompose8805194105218775978 config
1>networks:
1>  default:
1>    external:
1>      name: nat
1>services:
1>  test:
1>    build:
1>      context: C:\TEMP\test\test
1>      dockerfile: Dockerfile
1>    environment:
1>      ASPNETCORE_ENVIRONMENT: Development
1>    image: test
1>    ports:
1>    - 80/tcp
1>version: '3.0'
1>docker-compose -f "C:\TEMP\test\docker-compose.yml" -f "C:\TEMP\test\docker-compose.override.yml" -f "C:\TEMP\test\obj\Docker\docker-compose.vs.release.g.yml" -f "C:\TEMP\test\docker-compose.vs.release.yml" -p dockercompose8805194105218775978 config
1>networks:
1>  default:
1>    external:
1>      name: nat
1>services:
1>  test:
1>    build:
1>      args:
1>        source: obj/Docker/publish/
1>      context: C:\TEMP\test\test
1>      dockerfile: Dockerfile
1>    entrypoint: powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)
1>    environment:
1>      ASPNETCORE_ENVIRONMENT: Development
1>    image: test
1>    labels:
1>      com.microsoft.visualstudio.debuggee.arguments: ' --additionalProbingPath c:\.nuget\packages
1>        --additionalProbingPath c:\.nuget\fallbackpackages  test.dll'
1>      com.microsoft.visualstudio.debuggee.killprogram: powershell -Command if ((Get-Process
1>        dotnet -ErrorAction SilentlyContinue).Count -gt 0) { Stop-Process -Name dotnet
1>        }
1>      com.microsoft.visualstudio.debuggee.program: C:\Program Files\dotnet\dotnet.exe
1>      com.microsoft.visualstudio.debuggee.workingdirectory: C:\app
1>    ports:
1>    - 80/tcp
1>    volumes:
1>    - C:\Users\GilChen\onecoremsvsmon:C:\remote_debugger:ro
1>version: '3.0'
1>docker  ps --filter "status=running" --filter "name=dockercompose8805194105218775978_test_" --format {{.ID}} -n 1
1>test -> C:\TEMP\test\test\bin\Release\netcoreapp2.0\test.dll
1>test -> C:\TEMP\test\test\obj\Release\netcoreapp2.0\PubTmp\Out\
1>docker-compose -f "C:\TEMP\test\docker-compose.yml" -f "C:\TEMP\test\docker-compose.override.yml" -p dockercompose8805194105218775978 build
1>Building test
1>Step 1/6 : FROM microsoft/aspnetcore:2.0
1> ---> 0341c2b65536
1>Step 2/6 : ARG source
1> ---> Using cache
1> ---> 6e2f1ecc725f
1>Step 3/6 : WORKDIR /app
1> ---> Using cache
1> ---> 17119b545ab9
1>Step 4/6 : EXPOSE 80
1> ---> Using cache
1> ---> 3c2b519c6ea6
1>Step 5/6 : COPY ${source:-obj/Docker/publish} .
1> ---> Using cache
1> ---> 694943252acf
1>Step 6/6 : ENTRYPOINT dotnet test.dll
1> ---> Using cache
1> ---> 900440e42b57
1>Successfully built 900440e42b57
1>Successfully tagged test:latest
1>C:\WINDOWS\System32\WindowsPowerShell\v1.0\powershell.exe -NonInteractive -NoProfile -WindowStyle Hidden -ExecutionPolicy RemoteSigned -File "C:\Users\GilChen\AppData\Local\Temp\GetVsDbg.ps1" -Version vs2017u1 -RuntimeID debian.8-x64 -InstallPath "C:\Users\GilChen\vsdbg"
1>Info: Using vsdbg version '15.1.10630.1'
1>Info: Using Runtime ID 'linux-x64'
1>Info: Latest version of VsDbg is present. Skipping downloads
1>docker-compose -f "C:\TEMP\test\docker-compose.yml" -f "C:\TEMP\test\docker-compose.override.yml" -f "C:\TEMP\test\obj\Docker\docker-compose.vs.debug.g.yml" -f "C:\TEMP\test\docker-compose.vs.debug.yml" -p dockercompose8805194105218775978 kill
1>docker-compose -f "C:\TEMP\test\docker-compose.yml" -f "C:\TEMP\test\docker-compose.override.yml" -f "C:\TEMP\test\obj\Docker\docker-compose.vs.debug.g.yml" -f "C:\TEMP\test\docker-compose.vs.debug.yml" -p dockercompose8805194105218775978 down --rmi local --remove-orphans
1>Removing dockercompose8805194105218775978_test_1 ...
1>[1A[2K
1>Removing dockercompose8805194105218775978_test_1 ... [32mdone[0m
1>[1BNetwork nat is external, skipping
1>docker-compose -f "C:\TEMP\test\docker-compose.yml" -f "C:\TEMP\test\docker-compose.override.yml" -f "C:\TEMP\test\obj\Docker\docker-compose.vs.release.g.yml" -f "C:\TEMP\test\docker-compose.vs.release.yml" -p dockercompose8805194105218775978 up -d --no-build
1>Creating dockercompose8805194105218775978_test_1 ...
1>Creating dockercompose8805194105218775978_test_1
1>[1A[2K
1>Creating dockercompose8805194105218775978_test_1 ... [31merror[0m
1>[1B
1>ERROR: for dockercompose8805194105218775978_test_1  Cannot start service test: container 3dd36bc1170980c40edbc4244d9e18beb4ee09d033d918a10dab0750ec8dc9a1 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)","User":"ContainerUser","WorkingDirectory":"C:\\app","Environment":{"ASPNETCORE_ENVIRONMENT":"Development","ASPNETCORE_PKG_VERSION":"2.0.3","ASPNETCORE_URLS":"http://+:80"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
1>ERROR: for test  Cannot start service test: container 3dd36bc1170980c40edbc4244d9e18beb4ee09d033d918a10dab0750ec8dc9a1 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)","User":"ContainerUser","WorkingDirectory":"C:\\app","Environment":{"ASPNETCORE_ENVIRONMENT":"Development","ASPNETCORE_PKG_VERSION":"2.0.3","ASPNETCORE_URLS":"http://+:80"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
1>Encountered errors while bringing up the project.
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : Creating dockercompose8805194105218775978_test_1 ... 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : Creating dockercompose8805194105218775978_test_1
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : [1A[2K
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : Creating dockercompose8805194105218775978_test_1 ... [31merror[0m
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : [1B
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : ERROR: for dockercompose8805194105218775978_test_1  Cannot start service test: container 3dd36bc1170980c40edbc4244d9e18beb4ee09d033d918a10dab0750ec8dc9a1 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)","User":"ContainerUser","WorkingDirectory":"C:\\app","Environment":{"ASPNETCORE_ENVIRONMENT":"Development","ASPNETCORE_PKG_VERSION":"2.0.3","ASPNETCORE_URLS":"http://+:80"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : ERROR: for test  Cannot start service test: container 3dd36bc1170980c40edbc4244d9e18beb4ee09d033d918a10dab0750ec8dc9a1 encountered an error during CreateProcess: failure in a Windows system call: The system cannot find the file specified. (0x2) extra info: {"CommandLine":"powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)","User":"ContainerUser","WorkingDirectory":"C:\\app","Environment":{"ASPNETCORE_ENVIRONMENT":"Development","ASPNETCORE_PKG_VERSION":"2.0.3","ASPNETCORE_URLS":"http://+:80"},"CreateStdInPipe":true,"CreateStdOutPipe":true,"CreateStdErrPipe":true,"ConsoleSize":[0,0]}
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : Encountered errors while bringing up the project.。
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : 
1>C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.Docker.Sdk\build\Microsoft.VisualStudio.Docker.Compose.targets(346,5): error : 如需更多故障排除信息，请转到 http://aka.ms/DockerToolsTroubleshooting
1>已完成生成项目“docker-compose.dcproj”的操作 - 失败。
========== 生成: 成功或最新 0 个，失败 1 个，跳过 0 个 ==========
```

docker file is

```
FROM microsoft/aspnetcore:2.0
ARG source
WORKDIR /app
EXPOSE 80
COPY ${source:-obj/Docker/publish} .
ENTRYPOINT ["dotnet", "test.dll"]
```

docker-compose.yml
```
version: '3'

services:
  test:
    image: test
    build:
      context: ./test
      dockerfile: Dockerfile

```
docker-compose.override.yml
```
version: '3'

services:
  test:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "80"
networks:
  default:
    external:
      name: nat
```

docker-compose.vs.debug.yml
```
version: '3'

services:
  test:
    image: test:dev
    build:
      args:
        source: obj/Docker/empty/
    environment:
      - DOTNET_USE_POLLING_FILE_WATCHER=1
      - NUGET_PACKAGES=C:\.nuget\packages
      - NUGET_FALLBACK_PACKAGES=c:\.nuget\fallbackpackages
    volumes:
      - C:\TEMP\test\test:C:\app
      - C:\Users\GilChen\onecoremsvsmon:C:\remote_debugger:ro
      - C:\Users\GilChen\.nuget\packages\:C:\.nuget\packages:ro
      - C:\Program Files\dotnet\sdk\NuGetFallbackFolder:c:\.nuget\fallbackpackages:ro

    entrypoint: powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\Program Files\\dotnet\\dotnet.exe"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath c:\\.nuget\\packages --additionalProbingPath c:\\.nuget\\fallbackpackages  bin/Debug/netcoreapp2.0/test.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "powershell -Command if ((Get-Process dotnet -ErrorAction SilentlyContinue).Count -gt 0) { Stop-Process -Name dotnet }"

```
docker-compose.vs.release.yml
```
version: '3'

services:
  test:
    build:
      args:
        source: obj/Docker/publish/
    volumes:
      - C:\Users\GilChen\onecoremsvsmon:C:\remote_debugger:ro
    entrypoint: powershell -Command [System.Threading.Thread]::Sleep([System.Threading.Timeout]::Infinite)
    labels:
      com.microsoft.visualstudio.debuggee.program: "C:\\Program Files\\dotnet\\dotnet.exe"
      com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath c:\\.nuget\\packages --additionalProbingPath c:\\.nuget\\fallbackpackages  test.dll"
      com.microsoft.visualstudio.debuggee.workingdirectory: "C:\\app"
      com.microsoft.visualstudio.debuggee.killprogram: "powershell -Command if ((Get-Process dotnet -ErrorAction SilentlyContinue).Count -gt 0) { Stop-Process -Name dotnet }"


```
