### ISSUE TITLE
Please allow extra command line parameters to be passed to docker-compose

### ISSUE THREAD

**Issue by AceHack** [Microsoft/DockerTools#75]
It would be great to allow extra command line parameters

**Comment by yanchenw** [comment]
There is one work around you can do right now.
Open the generated obj\Docker\docker-compose.vs.debug.g.yml, if you want to override anything in here, create docker-compose.vs.debug.yml alongside with docker-compose.yml, override anything you want there, in your case, you will want to override the com.microsoft.visualstudio.debuggee.arguments.

For example, if I want to add a parameter to my dotnet core console application, I'll do the following:
```
version: '3.4'

services:
  foo:
    labels:
        com.microsoft.visualstudio.debuggee.arguments: " --additionalProbingPath c:\\.nuget\\packages --additionalProbingPath c:\\.nuget\\fallbackpackages  bin\\Debug\\netcoreapp2.0\\ConsoleApp4.dll bar"
```
