### ISSUE TITLE
Using a docker repository with port results in a wrong imagename in VS

### ISSUE THREAD

**Issue by WolfspiritM** [Microsoft/DockerTools#88]
Hi,

I was using a local docker repository but that seems to break things when using a port for that.

I remember there was a bug that tags didn't get honored it seems like that issue is related and the fix for it is now breaking in my case.

For example I've set my docker-compose like that:
```yaml
version: '3.4'

services:
  service1:
    image: localhost:5000/service1:latest
    build:
      context: .
      dockerfile: src/Services/Service1/Dockerfile

  service2:
    image: localhost:5000/service2:latest
    build:
      context: .
      dockerfile: src/Services/Service2/Dockerfile
```

Visual Studio seems to cut on the first ":" and the final image in both cases ends up being:
 ```localhost:dev``` which is wrong.
